---
- hosts: mywebserver1
  become: yes
  tasks:
  - include_tasks: myfilee.yaml

  # - name: i want to install web server
  #   apt:
  #     name: "{{ubuntuwebpack}}"
  #     state: "{{present}}"
  
  # - name: restart webserver
  #   service:
  #     name: "{{ubuntuwebpack}}"
  #     state: restarted
