---
- hosts: all
  become: yes
  tasks:
  - name: i want to ping all hosts
    ping:
  - name: i want to install tree
    apt:
      name: tree
      state: present
  - name: i want to install wget
    apt:
      name: wget
      state: present